### ISSUE TITLE
How to build it in Windows?

### ISSUE THREAD

**Issue by jerinka** [PatWie/tensorflow-cmake#21]
Hi this is a very helpful project, what changes needed to build this in windows too?

**Comment by PatWie** [comment]
I do not use Windows at all.
As written here:

https://github.com/PatWie/tensorflow-cmake/blob/c5032890978b9bc26b9d5bdf2787e8552d17cebb/cmake/modules/FindTensorFlow.cmake#L49-L53

I wonder if this would work in Windows. But I guess it is not working without changes. Did you gave it a shot under windows?
