### ISSUE TITLE
CMake: Find Tensorflow not working

### ISSUE THREAD

**Issue by dvicini** [PatWie/tensorflow-cmake#23]
Hi, 

it seems that a recent commit broke the `FindTensorflow.cmake` script. In Line 56 in `FindTensorflow.cmake`, the Python executable is declared as an `option`. However, from my understanding, options are boolean variables. When I insert a print statement, i.e. `message(FATAL_ERROR "${PYTHON_EXECUTABLE}")`, I just get `OFF` as an output, instead of `python3`. I am not a CMake expert, but wouldn't it be more appropriate to just set a variable, instead of using `option`?

Delio

**Comment by PatWie** [comment]
It does work

https://github.com/PatWie/tensorflow-cmake/blob/c5032890978b9bc26b9d5bdf2787e8552d17cebb/.drone.yml#L7

But I agree, there should be a different way.

**Comment by PatWie** [comment]
Fixed
27c267de333c132981192ce7b84bca2dfd3a3bad
