### ISSUE TITLE
Building dll with cuda 10

### ISSUE THREAD

**Issue by ttdd11** [PatWie/tensorflow-cmake#36]
Great repo!

Have you tried building tensorflow_cc.dll with gpu options?

**Comment by PatWie** [comment]
There is no windows support yet as I cannot test it and I never had the need to do so.

**Comment by PatWie** [comment]
But the tests are using CUDA10

https://github.com/PatWie/tensorflow-cmake/blob/c50be3f097a8d213f235a337eddc9af99671ef2e/.drone.yml#L19-L29
