### ISSUE TITLE
Clear documentation on what needs to be done from built from sources

### ISSUE THREAD

**Issue by deeptf** [PatWie/tensorflow-cmake#41]
Can you provide clear documentation on what exactly needs to be in Build folder?
Seems like the commands to copy just .so file and cc/ops/*.h does not suffice. 

"tensorflow-cmake/examples/simple/example.cc:2:49: fatal error: tensorflow/cc/client/client_session.h: No such file or directory"

This Seems to be present only in the source directory; This is very confusing

**Comment by PatWie** [comment]
The documentation is here
https://github.com/PatWie/tensorflow-cmake/blob/master/dockerfiles/Dockerfile.tensorflow-plain

Please have a look at the Docker files.
