### ISSUE TITLE
2.0 Support?

### ISSUE THREAD

**Issue by stekyne** [PatWie/tensorflow-cmake#52]
Is there any plans to have 2.0 support and if not soon, how to go about adding it myself?

Thanks

**Comment by PatWie** [comment]
TensorFlow 2.0 is a huge disappointment and disaster. 
I will have another look when TensorFlow 3.0 is released and use PyTorch in the meantime.

So no plans from my side and I haven't looked into how to support TF 2.0. What do you need?
For customs-ops [TensorFlow-Addons](https://github.com/tensorflow/addons) might be helpful.

Maybe there will be a `pytorch-cmake` soon.

**Comment by rustyx** [comment]
Why is TensorFlow 2.0 is a huge disappointment and disaster, if I may ask? :)
